services:

  mysql:
    image: chelloju/roboshop-mysql:1.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - roboshop
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - roboshop

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
    networks:
      - roboshop

  mongodb:
    image: chelloju/roboshop-mongodb:1.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - roboshop

  catalogue:
    image: chelloju/roboshop-catalogue:1.0
    restart: unless-stopped
    environment:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - roboshop

  cart:
    image: chelloju/roboshop-cart:1.0
    restart: unless-stopped
    environment:
      REDIS_HOST: "redis"
      CATALOGUE_HOST: "catalogue"
      CATALOGUE_PORT: "8080"
    depends_on:
      - redis
      - catalogue
    networks:
      - roboshop

  user:
    image: chelloju/roboshop-user:1.0
    restart: unless-stopped
    environment:
      MONGO: "true"
      REDIS_URL: "redis://redis:6379"
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
      - mongodb
      - redis
    networks:
      - roboshop

  shipping:
    image: chelloju/roboshop-shipping:1.0
    restart: unless-stopped
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: "mysql"
    depends_on:
      mysql:
        condition: service_healthy
      cart:
        condition: service_started
    networks:
      - roboshop

  payment:
    image: chelloju/roboshop-payment:1.0
    restart: unless-stopped
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: ${RABBITMQ_DEFAULT_USER}
      AMQP_PASS: ${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - cart
      - user
      - rabbitmq
    networks:
      - roboshop

  frontend:
    image: chelloju/roboshop-frontend:1.0
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    networks:
      - roboshop

volumes:
  mysql-data:
  mongo-data:

networks:
  roboshop:
    driver: bridge